serverless/utils

src/common/index.js, src/common/sleep.js, src/common/sleep.test.js, src/index.js
This PR adds a sleep function that can be used if some delay is needed before executing another function, e.g. retrying removal.
Example use case: https://github.com/serverless/components/pull/285/files#diff-6795bf000e41af98e7c3371a5da272d9R113
=> Add sleep function

README.md, docs/log.md, log.js, package.json, test/log.test.js
Adds general logging utility that will be used by `serverless/serverless` (and potentially other projects in the future) as specified in https://github.com/serverless/serverless/issues/8444
Closes: #63
=> feat: Add general logging utility

config.js, docs/config.md, package.json, test/config.js, test/process-backend-notification-request.js
Notifications tests had to be adjusted because they became nondeterministic - in some cases, the `lastShown` date for two notifications was the same and not the one that was expected was returned.
It introduces the following breaking changes:
- Removed `getGlobalConfig` from API
- removed support for all `rc`-discoverable files
- update not always modify only global config (if local is present, it's the one that will get updated)
Closes: #69
=> feat(Config): Introduce new config resolution

account.js, config.js, docs/account.md, package.json, test/account.js, test/config.js
Adds account-related methods as described in linked issue. 
I've made a decision to depend on injected `sdk` instance, which is supposed to be an instance of `ServerlessSDK` from `@serverless/platform-client` library. It is aimed to be temporary solution, which will be cleaned up when `components`, `enterprise-plugin` and `serverless` will be moved into one repository. 
Closes: #72
=> feat: Add account-related methods

analytics-and-notfications-url.js
We would like to record events from `CI` as well as we plan to introduce CI detection and enrich analytics events with that information
Note: The plan is to release it as a major version to avoid changing behavior for older versions which won't include information about `CI`
=> feat: Do not return `null` as analyticsUrl for CI=true

inquirer/index.js
BREAKING CHANGE: Inquirer prompt will have no prefix instead of `Serverless:`
If you wish, to still use `Serverless:` prefix, override it on the client side.
Related to: https://github.com/serverless/serverless/issues/9367
=> Remove `Serverless:` prefix from `inquirer`

docs/log.md, log.js, test/log.js
Needed in order to allow customizing log in interactive CLI outputs, related to: https://github.com/serverless/serverless/issues/9367
=> Support disabling entity in `log` util

docs/account.md, docs/telemetry.md, telemetry.js, test/telemetry.js
Add `StepHistory` class as it has to be reused between `dashboard-plugin` and `serverless`
=> feat: Add `StepHistory` class

docs/process-backend-notification-request.md, process-backend-notification-request.js, test/process-backend-notification-request.js
Introduce (`SLS_NOTIFICATIONS_MODE=3`) mode, with which notification as returned by backend is always shown to user (It's useful to test how backend resolves notifications in given service context).
Additionally
- Added more UX friendly notifications code notation (`off`, `upgrades-only`, `on`, `force`) maintaining support for old code
- Improved tests organization
Documentation update at https://github.com/serverless/serverless/pull/9755
=> Backend notifications: Introduce force display mode

inquirer/prompt-with-history.js, test/inquirer/prompt-with-history.js
As discussed in: https://github.com/serverless/serverless/pull/9768
=> Recognize continue prompts in history with `_continuation_`

docs/get-notifications-mode.md, get-notifications-mode.js, process-backend-notification-request.js, test/get-notifications-mode.js, test/process-backend-notification-request.js
Introduce separate `notifications` utils module in order to reuse `getNotificationsMode` method in Framework's telemetry (to report configured notifications mode) - related Framework PR: https://github.com/serverless/serverless/pull/9851
=> Introduce `notifications` module

docs/log.md, lib/log/join-text-tokens.js, log.js, test/lib/log/join-test-tokens.js, test/log.js
Addresses serverless/serverless#9860
Initially intention was to setup output registry as an event emitter (it's how e.g. event message logger internally works), still I think in this case we don't need to go that far (there's no viable use case where there can be two very different consumers of the output), hence I simply constructed it as function to be overridden with writing logic
=> Log: `writeText` interface

docs/log.md, lib/log/get-output-reporter.js, lib/log/get-progress-reporter.js, log.js, test/lib/log/get-output-reporter.js, test/lib/log/get-progress-reporter.js, test/log.js
Addresses: https://github.com/serverless/serverless/issues/9860
Additionally:
- Refactor `writeText` to rely on emitter interface in similar manner as `progress` (as same as it's with `progress` we need to create different instance and when processing invocations we need to be tell from which source they're coming from)
- Improve signature of events as send with `progress` updates.
=> Log: Plugin dedicated log & output writing interface

docs/log.md, lib/log-reporters/node/log-reporter.js, lib/log-reporters/node/progress-reporter.js, lib/log/join-text-tokens.js, log-reporters/node.js, log.js, package.json, test/lib/log/join-test-tokens.js, test/log-reporters/node.js
Addresses: serverless/serverless#9860
Additionally I've exposed `isInteractive` on `log`, in case we will need to tweak logs configuration in response to this environment characteristics. I hope it won't be the case, but current design proposes it.
=> Log: Node.js CLI reporter for dynamic progress

log.js
After releasing v5.8.0 tests in Framework suddenly started to fail.
It's the outcome of _innocent_  looking refactor made with: https://github.com/serverless/utils/commit/c7338bfc3cd9423c3fc8969bf20b938e03e6bdda
This effectively made our current logging not susceptible to `process.stdout.write` mocking, and that's done in numerous places in tests.
This patch fixes that
=> Log: Ensure writing functions respect mocked `stdout.write`

docs/log.md, lib/log-reporters/node/progress-reporter.js, log.js, test/log-reporters/node.js, test/log.js
A mean to indefinitely clear and close progress output, needed to be used especially when exception occurs
=> Log: `progress.clear` to clear and close progress output

docs/log.md, lib/log-reporters/node/progress-reporter.js, test/log-reporters/node.js
Addresses: serverless/serverless#9860
Returns special instance progress, dedicated to cover complete command progress. It shares same interface as any other progress item, but (through reporter implementation) it behaves differently:
- It's guaranteed to always be displayed at the top
- Time counter is displayed aside of it (starting counting from first update)
- It's not removed until command ends processing (`remove` is not effective, progress is cleared only after `progress.clear`)
=> Log: Main progress instance to cover entire command progress

docs/log.md, lib/log-reporters/node/style.js, log.js
When reviewing work done so far, I've observed that it'll be convienient to be able to setup constructs as:
```javascript
writeText(style.aside(
"First line",
"Second line",
"etc."
));
```
Providing multiline input that way is supported by `writeText`, but was not by style decorators, which when involved required using them on each line independently. This patch improves that interface
=> Log: Support multiline input in style decorators

CHANGELOG.md, package.json
It ensures we will rely on fixed version of `cli-progress-footer` (has fixed handling of that printing `.` issue)
=> Release v5.12.0

lib/log-reporters/node/log-reporter.js, test/log-reporters/node.js
Needed for https://github.com/serverless/serverless/pull/9960
=> Log: Do not write level prefix with deprecation warnings

log.js
@mnapoli observed that when relying on `log.success` from different `@serverless/utils` instance than one using by Framework, no decoration is applied.
This patch ensures that decorations are effective for all loaded instances of `@serverless/utils` (ofc all those which will come with this patch onboard)
=> Log: Ensure custom styles are applied globally

lib/log-reporters/node/log-reporter.js, log-reporters/node.js, test/log-reporters/node.js
Schema for commands is updated at https://github.com/serverless/serverless/pull/10197
=> v6: Log: Support for `--verbose` and `--debug` flags

inquirer/index.js, package.json
Upgrade dependencies that we can upgrade (we cannot upgrade to ESM only).
Additionally apply change proposed with https://github.com/serverless/utils/pull/75
=> Upgrade dependencies

README.md, docs/serverless-error.md, serverless-error.js, test/serverless-error.js
Handling of a new identity system will be added in the scope of this package, which should serve any CLIs as maintained by our organization.
In new authentication utils I'd like to throw user errors, yet, at this point, `ServerlessError` is only available in `serverless` package. This PR is to generalize `ServerlessError` so it can be used by any of our CLI's.
Additonally cleaned up main documentation
=> Serverless Inc. CLI's `ServerlessError` to report user errors

auth/login.js, auth/resolve-id-token.js, test/auth/resolve-id-token.test.js
- Support  providing `clientVersion` param to browser
- Update up to changed API spec
- Support `refreshToken` rotation by accepting returned new token from `auth/tokens/refresh` endpoint
=> Auth: Additional updates up to changes in implemented new indentity system

auth/login.js, auth/logout.js
Those utils can be used by some outer CLI, and we should not enforce our log messaging
=> Auth: Refactor utils to be CLI agnostic

api-request.js, commitlint.config.js, docs/api-request.md, test/api-request.test.js
- Support all HTTP `method`'s and provisioning of request `body`
- Configure error code for 4xx responses, and expose plain status on `httpStatusCode`
- Remove hardcoded URL prefix (breaking change, but API is still not in used, and implementation and at this point is considered as experimental)
- Improve debug logging
=> API: Generalize and improve `apiRequest` uti

api-request.js, test/api-request.test.js
Org token may not be supported for all operations, so in case of an `Unauthorized` error, it's good to communicate to users that they either use a wrong org token or should fallback to regular user login.
If `Unauthorized` happens on regular id token, show user error asking to re-login, instead of noisy programmer error listing direct response from the server. Such error can be the result of some reset on our authentication database side, or someone playing with the content of `.serverlessrc`
=> API: Improve authentication errors handling

auth/login.js
For telemetry purposes, we want to send information on what command originated the login (there are two options `onboarding` and `login`).
This patch opens support for `clientOriginCommand` param as passed by the invoking utility
=> Auth: Support `clientOriginCommand` param

auth/resolve-token.js
1. Prevent two parallel auth resolutions in the same process - as this may lead to one working with outdated auth tokens and producing 401 errors
2. Handle, if possible, cases where two parallel processes are authenticating with a console. In case of `refreshToken` mismatch, attempt to recover by retrieving authentication data as written by the other process
=> Auth: Fix race condition issues

console-ui.js, test/console-ui.js
Filter out the `stackTrace` tag from warning tags so that customers don't have to see it.
=> chore: Filter out stack trace from warning

console-ui.js, test/console-ui.js
🙄 I had this as `stacktrace` originally but copilot correct me to `stackTrace` and I believed it 🤖
=> fix: Stack trace should not be camel case

api-request.js, test/api-request.test.js
Adding a no auth option to the api request library so that we can make requests with out a bearer token. This is helpful when we have some config options that we don't need to be logged in to look up like the console layer environment keys 👍
=> feat: Added no auth option to apiRequest
