serverless/utils

.codecov.yml

This PR adds codecov.yml file to complete the codecov integration.

Add codecov.yml file

---

docs/API.md
src/base/arrayFlatten.js
src/data/append.js
src/data/append.test.js
src/data/assoc.js
src/data/assoc.test.js
src/data/filter.js
src/data/find.js
src/data/find.test.js
src/data/join.js
src/data/pick.js
src/data/prepend.js
src/data/prepend.test.js
src/data/set.js
src/data/set.test.js

Bug fixes for assoc, set, prepend, append and find.
Remove useless code from other methods.

Add a few bug fixes

---

docs/API.md
package-lock.json
package.json

This release includes changes in packaging that are required by the Lambda idempotency updates.

Releasing v0.0.20

---

CHANGELOG.md
analytics-and-notfications-url.js
package.json

- By default do not expose analytics url in CI environment
- Support override of analytics url via `SLS_ANALYTICS_URL` env var

Enhance analytics url handling

---

README.md
cloudformation-schema.js
docs/cloudformation-schema.md
package.json
test/cloudformation-schema.js

Addresses: https://github.com/serverless/serverless/issues/8627

Add cloudformationSchema util

---

cloudformation-schema.js
package.json
test/cloudformation-schema.js

- Upgrade `js-yaml` to v4
- Upgrade `@serverless/test` to v7 and `mocha` to v7
- Upgrade `sinon` to v9

Upgrade dependencies

---

package.json
process-backend-notification-request.js
test/process-backend-notification-request.js

Addresses: https://github.com/serverless/serverless/issues/9303

feat: Allow disabling backend notifications via env var

---

commitlint.config.js
docs/log.md
log.js
test/config.js
test/log.js

Addresses first item from https://github.com/serverless/serverless/issues/9860

Log: `legacy` interface (for logs to be shown conditionally)

---

log-reporters/node.js
test/log-reporters/node.js

Addresses: serverless/serverless#9860

Log: Node.js CLI reporter for substantial text output

---

docs/log.md
lib/log-reporters/node/log-reporter.js
lib/log-reporters/node/progress-reporter.js
lib/log-reporters/node/style.js
log-reporters/node.js
log.js
test/log-reporters/node.js
test/log.js

Single endpoint for all styles

Log: `style` decorators interface

---

lib/log-reporters/node/style.js

Log: Improve styles when just 16 or 256 colors are supported

---

docs/log.md
lib/log-reporters/node/progress-reporter.js
lib/log/get-progress-reporter.js
test/lib/log/get-progress-reporter.js

So through option we can indicate progress events that should be also reflected in logs feed

Log: Generalize handling of main process events

---

lib/log-reporters/node/style.js
log.js
package.json
test/log-reporters/node.js
test/log.js

- _notice_ level decorators `success` and `skip`
- `link` style decorator

Log: Style extensions

---

lib/log-reporters/node/style.js
log.js

By default it writes at `info`, while in our case we want `notice` level to be default

Log: Update main log function to write at `notice` level

---

log-reporters/node.js

Fixes https://github.com/serverless/serverless/issues/10381

Log: Ensure no doubled setup of log reporter

---

config.js

When attempting to test https://github.com/serverless/serverless/pull/10527, I've noticed that we missed logs refactor in utils package. This PR addresses that

Log: Configure modern logs for config handling

---

auth/get-org-id.js
auth/is-authenticated.js
auth/login.js
auth/resolve-id-token.js
docs/auth.md
test/auth/get-org-id.test.js
test/auth/is-authenticated.test.js

- Improve error handling conventions
- Fix error code in `resolveIdToken`
- `getOrgId` utility
- `isAuthenticated` utility

Auth: Additional utils and improvements

---

api-request.js
auth/resolve-mode.js
auth/resolve-token.js

Configure debug log, to help investigate issues related to authentication

Auth: Add debug logs

---

api-request.js
auth/resolve-token.js

fix: correct serverless error typo

---

lib/auth/urls.js

Added dev mode socket urls so we can use them in serverless framework.

feat: Added dev mode socket urls

---

CHANGELOG.md
package.json

Release change to event processing 😄

chore: Release v6.9.1

---

api-request.js

Allow custom accessKey to be used as authorization header when making requests

feat: Allow accessKey on console api

---

CHANGELOG.md
package.json

Releasing so I can start working on the deploy hook that integrates with dashboard

chore: Releae v6.13.0

---

api-request.js

Allow us to set the authMethod as an option so we can use dashboard tokens

fix: Set dashboardToken when using dashboard token
